### PR TITLE
Register tweet component on blog posts

### PR DESCRIPTION
**Pull request by ghys**
+ a few suggestions for the last blog posts

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
@github-luckow-org @kaikreuzer

**Comment by ghys** [comment]
huh it doesn't work...

**Comment by github-luckow-org** [comment]
wohoo :)

**Comment by davidgraeff** [comment]
Can you also add a few sentences about this feature for future posts as docu somewhere?

**Pull request merged**
