### PR TITLE
Use SVG logos over PNG & Update Why section & Clean-Up images

### PR DESCRIPTION
**Pull request by florian-h05**
openhab/openhab-docs#2305 has to be merged after this PR!

- openHAB logo ZIP: Replace svg app icons with shrinked versions.
- Use SVG openHAB logos instead of PNG ones.
- Use SVG logos for the "Why - Runs Everywhere" section.
- Improve styling (padding, text alignment) for artwork page.
- Update links and text of the "Why" section.
- Remove unused images from .vuepress/public and don't migrate unsused images from openhab-docs repo.

### CODE REVIEW

**Comment by florian-h05** [comment]
@kaikreuzer I have also shrinked the SVG appicons in this PR, forgot them yesterday. Can you please have a look?

**Review by stefan-hoehn — APPROVED** [review]
LGTM, please @florian-h05 check again after the build.

**Comment by wborn** [comment]
Looks like this PR broke the logo in the community footer:

Screenshot_20240612_200649_Chrome

**Comment by kaikreuzer** [comment]
I just fixed it!

**Comment by ghys** [comment]
Thanks @kaikreuzer - since [Twitter is officially X.com now](https://www.theverge.com/2024/5/17/23829098/twitter-x-com-url-links-switch) I think we can replace these Twitter logos with the X ones on all of our websites.
If openHAB has a presence on other platforms (Mastodon, Discord...) we could add these as well.

**Comment by kaikreuzer** [comment]
@ghys Done!

**Comment by kaikreuzer** [comment]
Website should be addressed by https://github.com/openhab/website/pull/473

**Pull request merged**
