### PR TITLE
[WIP] Add chatbot to website

### PR DESCRIPTION
**Pull request by kaikreuzer**
This adds a chatbase.io-based chatbot to our website, which is powered by ChatGPT.

### CODE REVIEW

**Comment by digitaldan** [comment]
Cool!

**Review by ghys — APPROVED** [review]
Looks like it works nicely now, I'll let you merge whenever you're ready or if as discussed we need to amend our privacy policy first as they might collect tracking data. Their policy is at https://www.chatbase.co/privacy.

**Comment by stefan-hoehn** [comment]
Depends on #410

**Comment by kaikreuzer** [comment]
@puresick Is your question why or when?
It was actually just me playing around a bit last year. I am not sure whether this service is still interesting and worth the money, so I might as well simply close the PR again.

**Comment by puresick** [comment]
@kaikreuzer My question is why this is going to be added to the webpage in the context of which benefits this integration will have for people visiting the webpage?

**Pull request closed without merging**
