### PR TITLE
Update addon logos

### PR DESCRIPTION
**Pull request by mueller-ma**
I added some logos and updated the mihome icon to be square. Is there any recommended resolution for these logos?

Edit: I haven't tested this PR.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
The chosen resolution is always 100px height and width depending on the aspect ratio.

**Comment by kaikreuzer** [comment]
So I guess you should shrink the logos a bit and mySQL can be trimmed.

**Comment by kaikreuzer** [comment]
@ghys Please comment if you think that these specs are not ideal anymore for the new website - I had obviously defined them for the old one.

**Comment by ghys** [comment]
The logos embedded in the add-on pages have this CSS:
```css
.addon-logo {
    max-width: 250px!important;
    max-height: 250px!important;
```
I think 100px is a little small now. Also, on high-dpi ("retina") screens, the bigger the resolution, the more "crisp" it will appear. See for instance the openHAB logo in the top-left corner.

**Comment by kaikreuzer** [comment]
> Also be aware you still need to https://github.com/openhab/openhab-docs/tree/gh-pages/images/addons too for now

That's a bit nasty as we have to commit the logos in both repos...

**Comment by ghys** [comment]
> But we should also limit the size to e.g. 20-30KB per logo, wdyt?

Yes, definitely.

> That's a bit nasty as we have to commit the logos in both repos...

They could be moved by the migration script indeed.

**Comment by ghys** [comment]
@mueller-ma would it be possible to reduce the size of the logos to 50KB max. (ideally 30KB)?

Also please change the base to master now for this PR, you can do this with the edit link near the title above.

**Comment by kaikreuzer** [comment]
I can take care of that as I am just working on a few logos anyhow.

**Comment by ghys** [comment]
I'll actually close this one, because I'm going to remove the logos from the website repo make the prepare-docs scripts copy them over from openhab-docs/images/addons.
So you'll only have to add the logos to openhab-docs where it makes sense right now because you need them there to add the frontmatter.

**Pull request closed without merging**
