### PR TITLE
Fix styling of tabs in dark mode

### PR DESCRIPTION
**Pull request by florian-h05**
This fixes this styling issue: 

image

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by florian-h05** [comment]
Don't merge yet!
This is WIP.

**Comment by kaikreuzer** [comment]
Yep, I noticed that when I saw that I cannot merge it. 😆

**Comment by florian-h05** [comment]
@kaikreuzer Finally had the time to finish this, it looks like his now: https://deploy-preview-479--openhab.netlify.app/addons/integrations/openhabcloud/#examples

**Comment by florian-h05** [comment]
Hmm I just noticed it now looks different on mobile phones, but I personally like the new look of the tabbar better.

**Review by stefan-hoehn — APPROVED** [review]

**Pull request merged**
