### PR TITLE
Enhance rss sorting and dynamic feed meta

### LINKED ISSUE #328: Enhance feed representation
Looks good however the entries are not sorted in https://openhab.org/rss.xml (my RSS clients does sort them though), still it could maybe be done: see https://github.com/webmasterish/vuepress-plugin-feed#default-options

```js
  // optional sorting function for the entries. 
  // Gets the array entries as the input, expects the sorted array
  // as its output.
  // e.g.:   sort:  entries => _.reverse( _.sortBy( entries, 'date' ) ),
  // Don't forget to do a `const _ = require('lodash');` to be able to use `_`!

  sort: entries => entries,
```

Also https://github.com/openhab/website/blob/main/add-blog-meta.rb could add feed-specific metadata to posts, like `feed.author` and `feed.image`.

_Originally posted by @ghys in https://github.com/openhab/website/issues/313#issuecomment-1002123996_

### PR DESCRIPTION
**Pull request by Confectrician**
Fixes #328

@ghys could you have a lok at that ruby script?

I am no ruby pro and all my skills are related to the doc scripts, so some check would be useful here.

### CODE REVIEW

**Comment by ghys** [comment]
Looks good!
Note that the RSS output doesn't include the author (https://deploy-preview-329--openhab.netlify.app/rss.xml) and the Atom output doesn't include the image (https://deploy-preview-329--openhab.netlify.app/feed.atom), but that's probably a format limitation.

**Comment by Confectrician** [comment]
>Note that the RSS output doesn't include the author (https://deploy-preview-329--openhab.netlify.app/rss.xml) and the Atom output doesn't include the image (https://deploy-preview-329--openhab.netlify.app/feed.atom), but that's probably a format limitation.

Have seen that too, but as it gets processed to json correct, i am assuming that everything works as expected.

**Comment by ghys** [comment]
For the author to appear in RSS you need an e-mail address, relevant code of the underlying library that generates the feeds:

https://github.com/jpmonette/feed/blob/34dbde9aa47b85ae207ba4fefe4c5794b8ca43e2/src/rss2.ts#L153-L164

Atom doesn't support images (there's no official element).

**Comment by Confectrician** [comment]
Hm then we can live without it. We don't have an email adress all the time.

**Pull request merged**
