### PR TITLE
Added binding xsd schemas from ESH to openHAB.

### LINKED ISSUE #156: Put binding schema xsd on openHAB website
The binding xsd point to eclipse smarthome. With the move of ESH to openHAB-core these schemas should also be updated I think.

I assume these should be put here on the website? What would be the desired location (So I can create a PR)? And is the list below complete?

I could find the following schemas:
__Binding__
```
<binding:binding id="<id>" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:binding="http://eclipse.org/smarthome/schemas/binding/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/binding/v1.0.0 http://eclipse.org/smarthome/schemas/binding-1.0.0.xsd">
```
__Thing__
```
<thing:thing-descriptions bindingId="<id>" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">
```

__Config__
```
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0 http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">
```

### PR DESCRIPTION
**Pull request by Hilbrand**
And renamed namespace to use openhab.org domain
Closes #156

### CODE REVIEW

**Comment by ghys** [comment]
Thanks @Hilbrand!
The build is broken now (not because of this PR, it's probably due to the move of the UIs), I'll have to take a look and will merge it afterwards.

**Comment by Hilbrand** [comment]
@ghys Build looks broken due to move of ui projects to their own repository (But that's something you already know :smile: ) Are you working on it or could you use some help here?

**Comment by ghys** [comment]
I opened https://github.com/openhab/openhab-docs/issues/904 to keep track of this, but so far nobody seems to have time to work on it ;)
If you have some shell scripting & Groovy scripts, and want to take a look - please be me guest 😄

**Comment by ghys** [comment]
Merging as the build is ✔️ again!
Thanks @Hilbrand :)

**Pull request merged**
