### PR TITLE
Update things database

### PR DESCRIPTION
**Pull request by ghys**
Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Just for my understanding: Where does this file come from...?

**Comment by ghys** [comment]
It's the output of https://github.com/openhab/website/blob/master/crawlthings.rb
I didn't include it in the CI process since it needs up-to-date clones of 4 repositories and that is maybe overkill...
Also it won't get its info from master branches, meaning there could be things not in the latest release included...
Not completely happy with this :)

**Comment by kaikreuzer** [comment]
So does that also crawl the Z-Wave things already?

**Comment by ghys** [comment]
Yes - actually I made this a month ago because I often wanted to know whether a ZWave device was supported by openHAB - I was unaware of the per-thing Markdown documents, only came across them recently by chance... :/

**Pull request merged**
