### PR TITLE
Sidebar refactoring

### PR DESCRIPTION
**Pull request by stefan-hoehn**
Adds the styles for the new hierarchy arrows in the sidebar which we introduced in https://github.com/openhab/openhab-docs/pull/2198 

@Confectrician it seems you were right that adding this style to openhab-docs isn't working.

### CODE REVIEW

**Comment by stefan-hoehn** [comment]
@kaikreuzer @ghys @Confectrician 

Can someone retrigger the build? Looking at the logs, it seems that there was a "Javascript out of heap memory" error.

btw, do we have a group like openhab-webui-maintainer, e.g. openhab-website-maintainers? if not, would that make sense?

**Comment by florian-h05** [comment]
> btw, do we have a group like openhab-webui-maintainer, e.g. openhab-website-maintainers? if not, would that make sense?

I thinkt the @openhab/foundation-staff team is responsible for the website content.

**Comment by ghys** [comment]
> that there was a "Javascript out of heap memory" error.

This happened before, we were always very tight with heap memory with VuePress. Migrating to the latest version/to VitePress could solve the problem.
The Netlify builds configurations already add a command line option to tell Node to increase the heap memory (I can't login at the time).

**Comment by florian-h05** [comment]
I am actually not sure if this PR is required.
Looking at some of the expandable sidebar entries on the next deployment, they are not greyed, but normally coloured:

IMG_2411

Looking at the docs-sidebar.js in the docs repo, these entries are defined in different ways, I’ll try out something and report back later.

**Review by kaikreuzer — APPROVED** [review]
Sure, thanks!

**Pull request merged**
