### PR TITLE
Reenable MQTT binding(s)

### PR DESCRIPTION
**Pull request by ghys**
Add 3 "hot replaces" in script

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
@davidgraeff @kaikreuzer could you maybe have a look:
https://deploy-preview-129--openhab-website.netlify.com/addons/bindings/mqtt/
https://deploy-preview-129--openhab-website.netlify.com/addons/bindings/mqtt.generic/
There's no way afaik to find mqtt.generic - maybe the doc page for the mqtt binding should have
`<!--list-subs-->`
(similarly to https://raw.githubusercontent.com/eclipse/smarthome/master/extensions/binding/org.eclipse.smarthome.binding.bluetooth/README.md).

The "code" description below the title in black looks weird too imho.

Finally since people will maybe still need the doc for the mqtt1 binding (which is still there but would now be hidden) maybe it makes sense to add a temporary notice on the page, something like:
```
::: tip
This is the new 2.x binding, replacing the now obsoleted 1.x binding whose documentation can still be found [here](../mqtt1/)
:::
```
(no need to add it to the source, I can do it here with the prepare-docs scripts, just asking for opinions)

**Comment by kaikreuzer** [comment]
>  maybe the doc page for the mqtt binding should have `<!--list-subs-->`

I agree!

> The "code" description below the title in black looks weird too imho.

Agree as well!

> Finally since people will maybe still need the doc for the mqtt1 binding (which is still there but would now be hidden)

This reminds me that I almost missed to move MQTT 1.x to the legacy addons now - just did it with https://github.com/openhab/openhab1-addons/pull/5735.

> it makes sense to add a temporary notice on the page

No, we do not do this on any of the other pages either. Also, the README file is at ESH and we should not add any links to the openHAB docs there.

@davidgraeff  Could you create a PR for the first two fixes in ESH? I could then merge it (if I create the PR myself, I am not allowed to merge...)

**Comment by kaikreuzer** [comment]
@davidgraeff Ping!

**Comment by davidgraeff** [comment]
Hm, I'm a little busy with the blog post https://github.com/davidgraeff/smarthomeday2018/edit/master/1_mqtt_openhab.md
on this snowy first advent.

And I do not see what needs to be done, to be honest. The markdown way to markup a block quote
is via ">" (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes) and
differs from code markup (three backticks).
The rendering engine should not put this into \<code\> tags and make it look like programming code.

Should I instead use the "::: tip" markup?

**Comment by davidgraeff** [comment]
https://github.com/eclipse/smarthome/pull/6684

**Comment by ghys** [comment]
> Blocks of code are either fenced by lines with three back-ticks ```, **or are indented with four spaces**.
(emphasis mine)

This is apparently what happens here, since there is no > to signify it's a block quote.

> Should I instead use the "::: tip" markup?

No, this is a specific syntax for the rendering engine on this website.

**Comment by davidgraeff** [comment]
I see. I have correct this for the generic mqtt thing readme in the given PR

**Comment by kaikreuzer** [comment]
@ghys I think this should now be merged - I'll trigger another docs-build tomorrow morning, which should then include the latest changes from the ESH README.

**Pull request merged**
