### PR TITLE
Use vector version of the openHAB logo

### PR DESCRIPTION
**Pull request by ecdye**
Related to <https://github.com/openhab/openhab-docs/pull/1558>

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by ecdye** [comment]
@Confectrician Are the images in `.vuepress/public` of openhab/openhab-docs migrates into this repo?

**Comment by ghys** [comment]
@ecdye no they are separate, the prod website has more of them in its own repo.

**Comment by ecdye** [comment]
Alright, so they all need to be replaced here as well, and as a follow up question, if the image is not used anywhere in its given repo then it can be deleted, right?

For example, `.vuepress/public/logo-white.png` exists in the openhanded/openhab-docs repo but is not used anywhere in that repo. Therefore, if it is not used in that repo it can be deleted, right?

**Comment by Confectrician** [comment]
If we can confirm that, yes.

All vuepress contents in the docs repo are just there to provide the preview.
I am not sure if it got the latest changes for theming already, so we have to keep an eye on that before removing files.

**Pull request closed without merging**
