### PR TITLE
Copy Google Assistant page + images from openhab-docs repo

### PR DESCRIPTION
**Pull request by ghys**
Add hot rewrite for wrong image relative path.

Related to https://github.com/openhab/openhab-docs/pull/721.
Related to https://github.com/openhab/openhab-docs/issues/690.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by Confectrician** [comment]
The edit this page link is wrong.

Currently:
`https://github.com/openhab/openhab-google-assistant/edit/master/USAGE.md`

Correct:
`https://github.com/openhab/openhab-google-assistant/edit/master/docs/USAGE.md`

**Comment by ghys** [comment]
Damn I thought https://github.com/openhab/website/pull/145/commits/76522e599df4815c5a2181d887be8f8796357aa3 too care of it.

**Comment by ghys** [comment]
Ok got it...
https://github.com/openhab/website/blob/62da9b7d1b8aac16e47034900e556fb37ed67198/prepare-docs.rb#L106
The source frontmatter in https://github.com/openhab/openhab-docs/tree/final/_addons_ios/google-assistant is wrong.

**Comment by Confectrician** [comment]
Will be corrected with the wrong image links.
I add it to the PR.

**Pull request merged**
