### PR TITLE
Show Java 17 required for testing as well as snapshot

### PR DESCRIPTION
**Pull request by rkoshak**
I tried to stick with what was there, but for consistency sake I wanted to change the conditions for docker to match those other two, being === 'stable" and !== 'stable' instead of (selectedVersion === 'testing' || selectedVersion === 'snapshot')

Solves #400 

I totally added the signed off to my commit. I don't know why DCO is failing, though these changes are pretty minimal.

### CODE REVIEW

**Comment by rkoshak** [comment]
The preview checks out. This is ready for review.

**Comment by hmerk** [comment]
@rkoshak 
We no longer really recommend Zulu OpenJDK, so we should overthink if we should provide any link here.

**Comment by Confectrician** [comment]
> I totally added the signed off to my commit. I don't know why DCO is failing, though these changes are pretty minimal.

I will take care of this and recognized the false flag for DCO Check.
This is probably related to your used email and if/how it is configured in your github account.

image

You may check the reason and further information on yourt own via `Checks` page, if you awant to investigate it yourself further.
Anyways it will not bother us for this PR

**Comment by Confectrician** [comment]
> so we should overthink if we should provide any link here.

This would probably be better discussed in a separate issue.
For now i would suggest to solve the definetely wrong recommendation with proper links and maybe remove them later, if we really want to.

**Comment by rkoshak** [comment]
> This is probably related to your used email and if/how it is configured in your github account.

I've successfully passed DCO with my email configured as it is now in GitHub. I think that because I filed this one through the browser I inserted an extra space between "Signed-off-by:" and my name which caused DCO to choke.

I'm good with merging this and will open another issue to deal with the recommended Java issue.

**Review by Confectrician — APPROVED** [review]

**Pull request merged**
