### PR TITLE
Update OpenhabianSection.vue

### PR DESCRIPTION
**Pull request by ThomDietrich**
Stumbled over this while checking out the new page.

Eclipse has to be mentioned for Mosquitto as per their rules.
Imho openHABian offers an openHAB setup rather than a server.
The rightarrow after "Learn How" doesn't look good. May be worth to replace or improve. 

Besides that I have a few comments regarding the text:
In the headline you are using the word appliance. Are you certain it is correct in the context? I was expecting the docker path.
I am not a fan of "openHABian, the openHAB operating system" as it doesn't really make the point. Maybe you want to stay closer to the original phrasing "hassle-free setup" or "self-configuring". See: https://www.openhab.org/docs/installation/openhabian.html
Instead of the less prominent Pine I'd suggest to mention "Debian-based systems".

Let me know if you'd like my help improving the text.

From what I saw so far, the page is a big step! Kudos @ghys 

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by ghys** [comment]
Hi Thomas, nice to see you back, I know you had a busy semester, hope all went well!

I came up with those sentences and it was unchallenged so ended up on the site, but nothing is final obviously :) The term "appliance" was to emphasize the fact you could simply set it up and almost forget about the underlying OS, maybe it's a little strong. I like the other suggestions too.
I'll keep the PR open for now to continue the discussion until we're happy on the text.

**Comment by ThomDietrich** [comment]
Wdyt?

**Comment by ghys** [comment]
I made the text concise on purpose because of this 😄:
image
And the parallax library has some problems, makes it hard to do things like adjusting the height.
Besides, the "runs everywhere" point is made just above so I don't believe it's useful to repeat it.
I quite like the rest, like the fact it's not focused on openHABian specifically but on the ease of installation.

**Comment by ThomDietrich** [comment]
Took me a few seconds to understand "this". Yes that's unfortunate.
We could go as far and remove the second sentence. Those openHABian details are described in the article and "hassle-free openHABian image" already suggests that it's easy and pre-configured with special settings and software. If you agree, please add a commit.

Any idea how to solve the issue of the ill-placed arrow? Maybe it would be better to replace it by a font awesome symbol!?

**Comment by ghys** [comment]
I removed the second sentence. Now I'm wondering whether the link should go back to the openHABian article rather than the installation guide intro, since it's focused on openHABian again?

> Any idea how to solve the issue of the ill-placed arrow? Maybe it would be better to replace it by a font awesome symbol!?

http://xahlee.info/comp/unicode_arrows.html - Unicode has plenty of arrows ;)
I didn't have a fundamental problem with it but [U+279C HEAVY ROUND-TIPPED RIGHTWARDS ARROW](https://codepoints.net/U+279C) ➜  does look better indeed. It should be replaced everywhere it appears though.

Preview here: https://deploy-preview-30--openhab-website.netlify.com/

**Comment by ThomDietrich** [comment]
This arrow looks way better, problem solved 👌 

You removed the third, not second sentence 🙈

**Comment by ghys** [comment]
Ah right, that's the one I wanted to remove actually, and I thought that's what you meant too.
That 3rd sentence repeats the same thing as the "runs everywhere" in the "why openHAB" section above.

I quite like the second sentence though.

**Comment by ThomDietrich** [comment]
👍

**Comment by ghys** [comment]
This iteration LGTM!
Ready to merge if you are :)

**Pull request merged**
