### PR TITLE
 Navbar flash fix on home page, new hero image

### PR DESCRIPTION
**Pull request by ghys**
cleanup in components

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Sorry to complain, but I actually liked the old hero image better - the new phone is pretty huge, the old was a bit more decent. It feels imho a bit too dominant. Also, the charts are a bit distracting for being the very first impression. As the new phone still isn't an iPhone X, it also does not really look much more modern than the previous one...

**Comment by ghys** [comment]
In my defense, newer iPhones _are_ taller ;)
I also thought some of the demo sitemap menus were a little bit too "demoish", didn't really show a real-world example. And I have no idea how the app looks like on a iPhone X :)
 But I get your point - I reverted the image.

**Comment by mueller-ma** [comment]
1_framed

What about using an Android phone as the hero image?

**Comment by ghys** [comment]
I like it!
This also gives me an silly idea - when the new mobile-friendly UI will be ready, what about a live preview of the demo like on https://framework7.io/?

**Comment by kaikreuzer** [comment]
> what about a live preview of the demo

Definitely yes! This should then completely replace our demo server (which would only be used to serve this preview and for providing the demo sitemap to the native apps).

**Comment by Confectrician** [comment]
Fully agree. This looks very neat.

**Pull request merged**
